/**
 * ANTARDRISHTI — Semantic Sensitivity — Provenance Types
 *
 * DetectionSource and SensitivityDecision are the shared evidence
 * schema used by ALL detection paths (deterministic, semantic,
 * neural, visual). The rest of the system depends only on these
 * types — not on which specific detector generated the result.
 */

// ── Detection source ──────────────────────────────────────────

/** Which detector(s) produced this sensitivity decision. */
export type DetectionSource =
  | 'deterministic'  // pii-rules hard-coded recognizer
  | 'semantic'       // ContextSensitivityDetector (context-window scorer)
  | 'neural'         // NeuralNerDetector (ONNX model, optional)
  | 'visual'         // OCR + vision pipeline
  | 'combined';      // multiple sources agree

// ── Sensitivity decision ──────────────────────────────────────

/**
 * A fully resolved sensitivity decision with complete provenance.
 * Generated by the fusion layer; consumed by the sanitizer and
 * evidence panel. Never contains the raw protected value.
 */
export interface SensitivityDecision {
  /** Whether this content should be protected */
  sensitive: boolean;
  /** Top-level category (e.g. 'identity_document', 'financial', 'health') */
  category: string;
  /** Fine-grained subtype within category (e.g. 'passport', 'salary') */
  subtype?: string;
  /** Confidence in the sensitivity decision (0–1) */
  confidence: number;
  /** Which detector(s) contributed to this decision */
  source: DetectionSource;
  /** Individual detector/rule IDs that contributed (for audit) */
  detectorIds: string[];
  /** DOM node ID if applicable */
  nodeId?: string;
  /** Visual region ID if applicable */
  regionId?: string;
  /** Character offset range in source text, if applicable */
  span?: { start: number; end: number };
  /** Human-readable provenance label shown in the evidence panel */
  reasoning: string;
  /** Policy decision derived from this finding */
  policyDecision?: 'tokenize' | 'redact' | 'allow' | 'block';
}
